### ISSUE TITLE
Convert Variables to yaml

### ISSUE THREAD

**Issue by GregHib** [GregHib/void#164]
All of the variables (varp, varc, varcstr etc..) found at the top of scripts are very similar in structure and static after found, and it would be useful to be able to add new one's on the fly when writing content.

```yaml
one:
  id: 1234
  type: varbit
prayers:
  id: 1584
  type: varp
  persistent: true
  list: [ normal, curses ]
```
