### ISSUE TITLE
Move animation and graphic parameters into configs

### ISSUE THREAD

**Issue by GregHib** [GregHib/void#171]
Mainly graphic height's and delays, could also do the same for projectiles (take delay from anim defs and height offset shooter).
No reason why most of these values can't be stored in configs; unless they're used multiple times with different values (which they're probably not?)

```yaml
graphic:
  id: 1234
  height: 100
  delay: 42
```
