### ISSUE TITLE
Door mechanics and player data

### ISSUE THREAD

**Issue by Syntax2022** [GregHib/void#469]
- How would i make the warriors guild main door behave more like runescape, I am currently working on warriors guild and the main door should not open unless the player's attack and strength = 120 in RuneScape and the behaviour I am looking for is if a player clicks a door the player will walk through the door making the door auto open and closed once the player has walked through the door right now the door states are global

Here's a gif that explains what i mean

![openingdoor](https://github.com/GregHib/void/assets/79747812/366662f8-2b33-4fa0-b0ff-6ab40426728d)

- what's the best practices for saving data to player files for instance in Warriors Guild i need the ability to save the current defender the player has gotten permanently to the players file so they won't need them in the inventory

- last question if an NPC doesn't have any animation at all e.g attack, spawn, death animation is this a cache issue? when adding the NPC to the `npc.yml` file i have 

```yml
animated_bronze_armour:
  id: 4278
  att: 10
  str: 10
  def: 10
  attack_speed: 4
  hitpoints: 100
  max_hit_melee: 20
  style: crush
  immune_poison: true
  immune_venom: true
  hunt_mode: aggressive
  race: human
  examine: "Animated bronze armour."
```

I added `race: human` because i saw in `NPCDeath.kt` that it get's the npc race to get the correct animation and after doing this all of the animated armours still have no animations is there something i am missing?

example GIF below:

![npcnoanimation](https://github.com/GregHib/void/assets/79747812/c8db67ab-4163-4a3a-9bf4-6ddafd84a87d)
