### ISSUE TITLE
Item on Item interaction issues

### ISSUE THREAD

**Issue by Syntax2022** [GregHib/void#488]
There's a few issues with Item on Item interactions

1. If I were to have 14 cleaned guams and 14 vial of waters the check for a full inventory doesn't take into account that two items will be removed and replaced with one so it tell you you don't have enough space

![fullinventory](https://github.com/GregHib/void/assets/79747812/05011208-92d9-47d5-afbe-5713680f0603)

2. When adding `ticks: x` to an item in `item-on-item.yml` it doesn't seem to have any effect and the `weakQueue` looks like it defaulting to 1 tick and after making a few of x item it looks like a timer is being duplicated because instead of making it with a steady x tick it's making multiple in the same tick

example of what i have added to `item-on-item.yml`

```yml

guam_unf_potion:
  skill: herblore
  level: 3
  xp: 0.0
  ticks: 4
  remove: [ clean_guam, vial_of_water ]
  add: [ guam_potion_unf ]
  animation: mixing_potion
  message: "You put the Guam leaf into the Vial of water."
```

![makingissue](https://github.com/GregHib/void/assets/79747812/f9d9cc9b-bf3b-4e52-bc4e-12ab3395b25c)

3. if i were to have 13 guam leafs and 14 vial of waters the error message in-game "You don't have enough x to make this" x is showing as null

![image](https://github.com/GregHib/void/assets/79747812/2e66a18e-a7aa-48d1-87bb-619e073d46d6)

**Additional context**
i tried other items inside `item-on-item.yml` and they all have the same issues i did this to make sure it wasn't something i did wrong and it was an actual bug
