### ISSUE TITLE
Max value to item on item 

### ISSUE THREAD

**Issue by Syntax2022** [GregHib/void#502]
**Description**
Inside `item-on-item.yml` there doesn't seem to be the ability to limit how many items a player can craft, for example inside the players inventory there are `1000 bolts` and `1000 opal tips` but for each craft I want to limit the player to only craft a max of 10 not `All`.

**Proposed solution**
Here is the solution I think would fit well inside `item-on-item.yml`

```yml
opal_bronze_bolts:
  skill: fletching
  level: 11
  xp: 16.0
  max: 10 <- max allow for craft
  remove:
    - item: bronze_bolts
    - item: opal_bolt_tips
      amount: 10
  add:
    - item: opal_bolts
      amount: 10
  animation: tipping_bolts
  message: "You fletch 10 bolts."
```
Putting `max` or `limit` instead of crafting the item every x tick till the item no longer exists, craft the item while 
`current < max`

**Considerations**
Another solution would be handling this in a script but `item-on-item.yml` is already very useful when it comes to these processes when using items on other items.

**Comment by GregHib** [comment]
Agreed something is missing here, but I think it's the option to skip the "make-x" interface as most of fetching doesn't use make-x

**Comment by Syntax2022** [comment]
Yeah, that makes more sense. Another thing I thought of is the ability to change the default text for example;

```yml
opal_bronze_bolts:
  skill: fletching
  level: 11
  xp: 16.0
  text: "How many batches of 10 would you like to make?" <- override default
  remove:
    - item: bronze_bolts
    - item: opal_bolt_tips
      amount: 10
  add:
    - item: opal_bolts
      amount: 10
  animation: tipping_bolts
  message: "You fletch 10 bolts."
```
Some item on item shows different text dialog
