### ISSUE TITLE
Allow hunt mechanics to have multiple targets

### ISSUE THREAD

**Issue by GregHib** [GregHib/void#566]
Nora T Hagg and Sorceress's Garden can target multiple players at once.

TODO:
- Change `HuntPlayer` NPC, Object & FloorItem to accept a list of target's but also randomly select one and leave it up to the calling code to decide which it wants to use

```kotlin
data class HuntPlayer(
    val mode: String,
    val targets: List<Player>,
    val target: Player
) : Event
```

Hunting.kt
```kotlin
val targets = getCharacters(npc, players, range, definition)
if (targets.isEmpty()) {
   continue
}
val target = targets.random(seed)
npc.emit(HuntPlayer(mode, targets, target))
```

```yaml
spotting:
  type: player
  check_visual: line_of_sight
  check_afk: false
  check_not_to_strong: false
  check_not_combat: false
  check_not_combat_self: false
  check_not_busy: false
  check_afk: false
  ```
